// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imwytmgtgusahmujhfpm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imltd3l0bWd0Z3VzYWhtdWpoZnBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNTE1OTQsImV4cCI6MjA1ODcyNzU5NH0.-AcIegtHGQCGohroU56dJCtCif9ZjaJOYat_9UxCOLs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);